/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SystemIndexRouteImport } from './routes/system/index'
import { Route as SslIndexRouteImport } from './routes/ssl/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as IncidentsIndexRouteImport } from './routes/incidents/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as ChartsIndexRouteImport } from './routes/charts/index'
import { Route as ServicesBulkImportRouteImport } from './routes/services/bulk-import'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfileOverviewRouteImport } from './routes/profile/overview'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileChangePasswordRouteImport } from './routes/profile/change-password'
import { Route as ProfileActivityRouteImport } from './routes/profile/activity'
import { Route as ContactsBulkImportRouteImport } from './routes/contacts/bulk-import'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthChangePasswordRouteImport } from './routes/auth/change-password'
import { Route as SystemTemplatesIndexRouteImport } from './routes/system/templates/index'
import { Route as SystemRolesIndexRouteImport } from './routes/system/roles/index'
import { Route as SystemLocationsIndexRouteImport } from './routes/system/locations/index'
import { Route as SystemCountriesIndexRouteImport } from './routes/system/countries/index'
import { Route as SystemBranchesIndexRouteImport } from './routes/system/branches/index'
import { Route as SystemLocationsBulkImportsRouteImport } from './routes/system/locations/bulk-imports'
import { Route as SystemLocationsBulkImportRouteImport } from './routes/system/locations/bulk-import'
import { Route as SystemCountriesBulkImportsRouteImport } from './routes/system/countries/bulk-imports'
import { Route as SystemCountriesBulkImportRouteImport } from './routes/system/countries/bulk-import'
import { Route as SystemBranchesBulkImportRouteImport } from './routes/system/branches/bulk-import'
import { Route as ContactsGroupIdMembersRouteImport } from './routes/contacts/$groupId.members'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => rootRouteImport,
} as any)
const SslIndexRoute = SslIndexRouteImport.update({
  id: '/ssl/',
  path: '/ssl/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsIndexRoute = ChartsIndexRouteImport.update({
  id: '/charts/',
  path: '/charts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBulkImportRoute = ServicesBulkImportRouteImport.update({
  id: '/services/bulk-import',
  path: '/services/bulk-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileOverviewRoute = ProfileOverviewRouteImport.update({
  id: '/profile/overview',
  path: '/profile/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileChangePasswordRoute = ProfileChangePasswordRouteImport.update({
  id: '/profile/change-password',
  path: '/profile/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileActivityRoute = ProfileActivityRouteImport.update({
  id: '/profile/activity',
  path: '/profile/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsBulkImportRoute = ContactsBulkImportRouteImport.update({
  id: '/contacts/bulk-import',
  path: '/contacts/bulk-import',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/auth/change-password',
  path: '/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemTemplatesIndexRoute = SystemTemplatesIndexRouteImport.update({
  id: '/system/templates/',
  path: '/system/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRolesIndexRoute = SystemRolesIndexRouteImport.update({
  id: '/system/roles/',
  path: '/system/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemLocationsIndexRoute = SystemLocationsIndexRouteImport.update({
  id: '/system/locations/',
  path: '/system/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemCountriesIndexRoute = SystemCountriesIndexRouteImport.update({
  id: '/system/countries/',
  path: '/system/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemBranchesIndexRoute = SystemBranchesIndexRouteImport.update({
  id: '/system/branches/',
  path: '/system/branches/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemLocationsBulkImportsRoute =
  SystemLocationsBulkImportsRouteImport.update({
    id: '/system/locations/bulk-imports',
    path: '/system/locations/bulk-imports',
    getParentRoute: () => rootRouteImport,
  } as any)
const SystemLocationsBulkImportRoute =
  SystemLocationsBulkImportRouteImport.update({
    id: '/system/locations/bulk-import',
    path: '/system/locations/bulk-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const SystemCountriesBulkImportsRoute =
  SystemCountriesBulkImportsRouteImport.update({
    id: '/system/countries/bulk-imports',
    path: '/system/countries/bulk-imports',
    getParentRoute: () => rootRouteImport,
  } as any)
const SystemCountriesBulkImportRoute =
  SystemCountriesBulkImportRouteImport.update({
    id: '/system/countries/bulk-import',
    path: '/system/countries/bulk-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const SystemBranchesBulkImportRoute =
  SystemBranchesBulkImportRouteImport.update({
    id: '/system/branches/bulk-import',
    path: '/system/branches/bulk-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactsGroupIdMembersRoute = ContactsGroupIdMembersRouteImport.update({
  id: '/contacts/$groupId/members',
  path: '/contacts/$groupId/members',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/contacts/bulk-import': typeof ContactsBulkImportRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/overview': typeof ProfileOverviewRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/services/bulk-import': typeof ServicesBulkImportRoute
  '/charts': typeof ChartsIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/incidents': typeof IncidentsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/services': typeof ServicesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/ssl': typeof SslIndexRoute
  '/system': typeof SystemIndexRoute
  '/users': typeof UsersIndexRoute
  '/contacts/$groupId/members': typeof ContactsGroupIdMembersRoute
  '/system/branches/bulk-import': typeof SystemBranchesBulkImportRoute
  '/system/countries/bulk-import': typeof SystemCountriesBulkImportRoute
  '/system/countries/bulk-imports': typeof SystemCountriesBulkImportsRoute
  '/system/locations/bulk-import': typeof SystemLocationsBulkImportRoute
  '/system/locations/bulk-imports': typeof SystemLocationsBulkImportsRoute
  '/system/branches': typeof SystemBranchesIndexRoute
  '/system/countries': typeof SystemCountriesIndexRoute
  '/system/locations': typeof SystemLocationsIndexRoute
  '/system/roles': typeof SystemRolesIndexRoute
  '/system/templates': typeof SystemTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/contacts/bulk-import': typeof ContactsBulkImportRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/overview': typeof ProfileOverviewRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/services/bulk-import': typeof ServicesBulkImportRoute
  '/charts': typeof ChartsIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/incidents': typeof IncidentsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/services': typeof ServicesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/ssl': typeof SslIndexRoute
  '/system': typeof SystemIndexRoute
  '/users': typeof UsersIndexRoute
  '/contacts/$groupId/members': typeof ContactsGroupIdMembersRoute
  '/system/branches/bulk-import': typeof SystemBranchesBulkImportRoute
  '/system/countries/bulk-import': typeof SystemCountriesBulkImportRoute
  '/system/countries/bulk-imports': typeof SystemCountriesBulkImportsRoute
  '/system/locations/bulk-import': typeof SystemLocationsBulkImportRoute
  '/system/locations/bulk-imports': typeof SystemLocationsBulkImportsRoute
  '/system/branches': typeof SystemBranchesIndexRoute
  '/system/countries': typeof SystemCountriesIndexRoute
  '/system/locations': typeof SystemLocationsIndexRoute
  '/system/roles': typeof SystemRolesIndexRoute
  '/system/templates': typeof SystemTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/contacts/bulk-import': typeof ContactsBulkImportRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/overview': typeof ProfileOverviewRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/services/bulk-import': typeof ServicesBulkImportRoute
  '/charts/': typeof ChartsIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/ssl/': typeof SslIndexRoute
  '/system/': typeof SystemIndexRoute
  '/users/': typeof UsersIndexRoute
  '/contacts/$groupId/members': typeof ContactsGroupIdMembersRoute
  '/system/branches/bulk-import': typeof SystemBranchesBulkImportRoute
  '/system/countries/bulk-import': typeof SystemCountriesBulkImportRoute
  '/system/countries/bulk-imports': typeof SystemCountriesBulkImportsRoute
  '/system/locations/bulk-import': typeof SystemLocationsBulkImportRoute
  '/system/locations/bulk-imports': typeof SystemLocationsBulkImportsRoute
  '/system/branches/': typeof SystemBranchesIndexRoute
  '/system/countries/': typeof SystemCountriesIndexRoute
  '/system/locations/': typeof SystemLocationsIndexRoute
  '/system/roles/': typeof SystemRolesIndexRoute
  '/system/templates/': typeof SystemTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/contacts/bulk-import'
    | '/profile/activity'
    | '/profile/change-password'
    | '/profile/edit'
    | '/profile/overview'
    | '/profile/settings'
    | '/services/bulk-import'
    | '/charts'
    | '/contacts'
    | '/dashboard'
    | '/incidents'
    | '/profile'
    | '/services'
    | '/settings'
    | '/ssl'
    | '/system'
    | '/users'
    | '/contacts/$groupId/members'
    | '/system/branches/bulk-import'
    | '/system/countries/bulk-import'
    | '/system/countries/bulk-imports'
    | '/system/locations/bulk-import'
    | '/system/locations/bulk-imports'
    | '/system/branches'
    | '/system/countries'
    | '/system/locations'
    | '/system/roles'
    | '/system/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/contacts/bulk-import'
    | '/profile/activity'
    | '/profile/change-password'
    | '/profile/edit'
    | '/profile/overview'
    | '/profile/settings'
    | '/services/bulk-import'
    | '/charts'
    | '/contacts'
    | '/dashboard'
    | '/incidents'
    | '/profile'
    | '/services'
    | '/settings'
    | '/ssl'
    | '/system'
    | '/users'
    | '/contacts/$groupId/members'
    | '/system/branches/bulk-import'
    | '/system/countries/bulk-import'
    | '/system/countries/bulk-imports'
    | '/system/locations/bulk-import'
    | '/system/locations/bulk-imports'
    | '/system/branches'
    | '/system/countries'
    | '/system/locations'
    | '/system/roles'
    | '/system/templates'
  id:
    | '__root__'
    | '/'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/contacts/bulk-import'
    | '/profile/activity'
    | '/profile/change-password'
    | '/profile/edit'
    | '/profile/overview'
    | '/profile/settings'
    | '/services/bulk-import'
    | '/charts/'
    | '/contacts/'
    | '/dashboard/'
    | '/incidents/'
    | '/profile/'
    | '/services/'
    | '/settings/'
    | '/ssl/'
    | '/system/'
    | '/users/'
    | '/contacts/$groupId/members'
    | '/system/branches/bulk-import'
    | '/system/countries/bulk-import'
    | '/system/countries/bulk-imports'
    | '/system/locations/bulk-import'
    | '/system/locations/bulk-imports'
    | '/system/branches/'
    | '/system/countries/'
    | '/system/locations/'
    | '/system/roles/'
    | '/system/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  ContactsBulkImportRoute: typeof ContactsBulkImportRoute
  ProfileActivityRoute: typeof ProfileActivityRoute
  ProfileChangePasswordRoute: typeof ProfileChangePasswordRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileOverviewRoute: typeof ProfileOverviewRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ServicesBulkImportRoute: typeof ServicesBulkImportRoute
  ChartsIndexRoute: typeof ChartsIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SslIndexRoute: typeof SslIndexRoute
  SystemIndexRoute: typeof SystemIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ContactsGroupIdMembersRoute: typeof ContactsGroupIdMembersRoute
  SystemBranchesBulkImportRoute: typeof SystemBranchesBulkImportRoute
  SystemCountriesBulkImportRoute: typeof SystemCountriesBulkImportRoute
  SystemCountriesBulkImportsRoute: typeof SystemCountriesBulkImportsRoute
  SystemLocationsBulkImportRoute: typeof SystemLocationsBulkImportRoute
  SystemLocationsBulkImportsRoute: typeof SystemLocationsBulkImportsRoute
  SystemBranchesIndexRoute: typeof SystemBranchesIndexRoute
  SystemCountriesIndexRoute: typeof SystemCountriesIndexRoute
  SystemLocationsIndexRoute: typeof SystemLocationsIndexRoute
  SystemRolesIndexRoute: typeof SystemRolesIndexRoute
  SystemTemplatesIndexRoute: typeof SystemTemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssl/': {
      id: '/ssl/'
      path: '/ssl'
      fullPath: '/ssl'
      preLoaderRoute: typeof SslIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/': {
      id: '/charts/'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bulk-import': {
      id: '/services/bulk-import'
      path: '/services/bulk-import'
      fullPath: '/services/bulk-import'
      preLoaderRoute: typeof ServicesBulkImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/overview': {
      id: '/profile/overview'
      path: '/profile/overview'
      fullPath: '/profile/overview'
      preLoaderRoute: typeof ProfileOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/change-password': {
      id: '/profile/change-password'
      path: '/profile/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof ProfileChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/activity': {
      id: '/profile/activity'
      path: '/profile/activity'
      fullPath: '/profile/activity'
      preLoaderRoute: typeof ProfileActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/bulk-import': {
      id: '/contacts/bulk-import'
      path: '/contacts/bulk-import'
      fullPath: '/contacts/bulk-import'
      preLoaderRoute: typeof ContactsBulkImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/auth/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/templates/': {
      id: '/system/templates/'
      path: '/system/templates'
      fullPath: '/system/templates'
      preLoaderRoute: typeof SystemTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/roles/': {
      id: '/system/roles/'
      path: '/system/roles'
      fullPath: '/system/roles'
      preLoaderRoute: typeof SystemRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/locations/': {
      id: '/system/locations/'
      path: '/system/locations'
      fullPath: '/system/locations'
      preLoaderRoute: typeof SystemLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/countries/': {
      id: '/system/countries/'
      path: '/system/countries'
      fullPath: '/system/countries'
      preLoaderRoute: typeof SystemCountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/branches/': {
      id: '/system/branches/'
      path: '/system/branches'
      fullPath: '/system/branches'
      preLoaderRoute: typeof SystemBranchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/locations/bulk-imports': {
      id: '/system/locations/bulk-imports'
      path: '/system/locations/bulk-imports'
      fullPath: '/system/locations/bulk-imports'
      preLoaderRoute: typeof SystemLocationsBulkImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/locations/bulk-import': {
      id: '/system/locations/bulk-import'
      path: '/system/locations/bulk-import'
      fullPath: '/system/locations/bulk-import'
      preLoaderRoute: typeof SystemLocationsBulkImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/countries/bulk-imports': {
      id: '/system/countries/bulk-imports'
      path: '/system/countries/bulk-imports'
      fullPath: '/system/countries/bulk-imports'
      preLoaderRoute: typeof SystemCountriesBulkImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/countries/bulk-import': {
      id: '/system/countries/bulk-import'
      path: '/system/countries/bulk-import'
      fullPath: '/system/countries/bulk-import'
      preLoaderRoute: typeof SystemCountriesBulkImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/branches/bulk-import': {
      id: '/system/branches/bulk-import'
      path: '/system/branches/bulk-import'
      fullPath: '/system/branches/bulk-import'
      preLoaderRoute: typeof SystemBranchesBulkImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$groupId/members': {
      id: '/contacts/$groupId/members'
      path: '/contacts/$groupId/members'
      fullPath: '/contacts/$groupId/members'
      preLoaderRoute: typeof ContactsGroupIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  ContactsBulkImportRoute: ContactsBulkImportRoute,
  ProfileActivityRoute: ProfileActivityRoute,
  ProfileChangePasswordRoute: ProfileChangePasswordRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileOverviewRoute: ProfileOverviewRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ServicesBulkImportRoute: ServicesBulkImportRoute,
  ChartsIndexRoute: ChartsIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SslIndexRoute: SslIndexRoute,
  SystemIndexRoute: SystemIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ContactsGroupIdMembersRoute: ContactsGroupIdMembersRoute,
  SystemBranchesBulkImportRoute: SystemBranchesBulkImportRoute,
  SystemCountriesBulkImportRoute: SystemCountriesBulkImportRoute,
  SystemCountriesBulkImportsRoute: SystemCountriesBulkImportsRoute,
  SystemLocationsBulkImportRoute: SystemLocationsBulkImportRoute,
  SystemLocationsBulkImportsRoute: SystemLocationsBulkImportsRoute,
  SystemBranchesIndexRoute: SystemBranchesIndexRoute,
  SystemCountriesIndexRoute: SystemCountriesIndexRoute,
  SystemLocationsIndexRoute: SystemLocationsIndexRoute,
  SystemRolesIndexRoute: SystemRolesIndexRoute,
  SystemTemplatesIndexRoute: SystemTemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
